### ISSUE TITLE
How would I download the whole dataset? 

### ISSUE THREAD

**Issue by zhizdev** [deepghs/cheesechaser#4]
Thanks for the awesome repo! 

Curious on how one would actually download this dataset. 

Would one do something like `resource_ids=range(0, 7359990),` when downloading? 

And how would one download the metadata associate with it? 

Thanks!

**Comment by narugo1992** [comment]
the `cheesechaser` library is designed for batch retreiving images, not including metadata.

and, if u need the entire dataset, my suggestion is to download the full archives (and metadata file) from the huggingface repository, that should be much faster than cheesechaser.

**Comment by zhizdev** [comment]
Thanks so much!
